services:
  app:
    build: ./app
    container_name: fastify_opti_app
    ports:
      - "3025:3025"
    network_mode: "host"
    environment:
      PORT: 3025
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: psql
      DB_NAME: mydb

  worker-post-fastify:
    build: ./app
    container_name: worker_post_fastify
    image: worker-post-fastify:latest
    network_mode: "host"
    command: node src/worker/checkoutPost.worker.js
