services:
  express-opti-app:
    build: ./express
    container_name: express_opti_app
    ports:
      - "3010:3010"
    network_mode: "host"
    environment:
      PORT: 3010
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: psql
      DB_NAME: mydb

  # worker-post-grpc:
  #   build: ./express
  #   container_name: worker-post-grpc
  #   image: worker-post-grpc:latest
  #   network_mode: "host"
  #   command: node src/worker/checkoutPost.worker.js
  #   environment:
  #     DB_HOST: 127.0.0.1
  #     DB_PORT: 5432
  #     DB_USER: postgres
  #     DB_PASSWORD: psql
  #     DB_NAME: mydb
  

  fastify-opti-app:
    build: ./fastify
    container_name: fastify-opti-app
    ports:
      - "3015:3015"
    network_mode: "host"
    environment:
      PORT: 3015
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: psql
      DB_NAME: mydb

  # worker-post:
  #   build: ./fastify
  #   container_name: worker-post
  #   image: worker-post:latest
  #   network_mode: "host"
  #   command: node src/worker/checkoutPost.worker.js
  #   environment:
  #     DB_HOST: 127.0.0.1
  #     DB_PORT: 5432
  #     DB_USER: postgres
  #     DB_PASSWORD: psql
  #     DB_NAME: mydb
  
  # grpc-server:
  #   build: ./grpc-server
  #   image: grpc-server:latest
  #   container_name: grpc_server
  #   ports:
  #     - "50051:50051"
  #   network_mode: "host"
  #   environment:
  #     DB_HOST: 127.0.0.1
  #     DB_PORT: 5432
  #     DB_USER: postgres
  #     DB_PASSWORD: psql
  #     DB_NAME: mydb



